sudo: required
os: linux
dist: xenial
arch:
- "amd64"
- "arm64"
language: python
python:
- "2.7"
- "3.4"
- "3.5"
- "3.6"
- "3.7"
- "pypy"
- "pypy3.5"
install:
- python -m pip install virtualenv
- python -m virtualenv .venv
- source .venv/bin/activate
- python -m pip install -r requirements.txt
- sudo -H pip install setuptools twine --upgrade
script:
- make test
- make local
after_success:
- codecov
deploy:
  provider: pypi
  user: alexdlaird
  password:
    secure: aVTgq5yalu4R/MAVHIpdd+5QxLyo4DlDNWsTOQxKQ44VdWrE5yFSNmrYRvcbzwht6ifKVc1Q5uZlQ5sCfuYo7JYaoxED4eyS//8V03t9/2NldHkJQ1RIIEWLSeLI5+7CoGnd/3Ei2oGf9aUMAWp/TY51SLwrC8wNCxI/3pCNLg82WSdYJOjlrHmZTPSi8F/mw1OtBwDepi0dYGriZexGaGp+pgc/ysWGLe6WHszwjoLQ3uj1VDabzh+ckfYPaclvLGZtEnypjq8/OXaX0ehsVPQYXZDUxRJEpeliyIQ8E1gc4xCUq13PjaV+OmcEK1sqxGWS9k1+c/pHOWSb2aRw2kVRh1/HSYI25B1xS30Q7z43F+hDXyLgRVvwgY1nkyLzQGzl9hGAs+/+rIAlGUW9W8vB1NCGL3k15mE+7F12aPzn0jLqqnUrxpLGsfC5CbLHXZ1xAp8nqYH7iK0fiqKau/R+MX3hSGjmsWdKUy/DZfeFsbCLiKOBvjg1Ru3cXE2V1F/GSx6wHVPEGK7hhxmlylRth4RkfxnBC9OerzAhyA2b4QmRlTseRL6AcgR/06qmO8BHyObHlizaBybU3Io+fxNq04bIjHQhhGlN+l9zX00y7Ww+/T+AquNn+aZPG5uUQdaHLzwnH5hPjjrsgm4ZgS2DDH/1waRScq2rwJkV2JU=
  on:
    tags: true
    python: 3.6
