os: linux
dist: xenial
language: python
python:
  - "2.7"
  - "3.5"
  - "3.6"
  - "3.7"
  - "3.8"
  - "3.9-dev"
  - "pypy"
  - "pypy3"
install:
  - python -m pip install virtualenv
  - python -m virtualenv venv
  - make install
script:
  - make test
  - make local
after_success:
  - codecov
before_deploy:
  - make docs
  - sudo -H python -m pip install setuptools twine --upgrade
  - make validate-release VERSION=$TRAVIS_TAG
deploy:
  provider: pypi
  username: alexdlaird
  password:
    secure: aVTgq5yalu4R/MAVHIpdd+5QxLyo4DlDNWsTOQxKQ44VdWrE5yFSNmrYRvcbzwht6ifKVc1Q5uZlQ5sCfuYo7JYaoxED4eyS//8V03t9/2NldHkJQ1RIIEWLSeLI5+7CoGnd/3Ei2oGf9aUMAWp/TY51SLwrC8wNCxI/3pCNLg82WSdYJOjlrHmZTPSi8F/mw1OtBwDepi0dYGriZexGaGp+pgc/ysWGLe6WHszwjoLQ3uj1VDabzh+ckfYPaclvLGZtEnypjq8/OXaX0ehsVPQYXZDUxRJEpeliyIQ8E1gc4xCUq13PjaV+OmcEK1sqxGWS9k1+c/pHOWSb2aRw2kVRh1/HSYI25B1xS30Q7z43F+hDXyLgRVvwgY1nkyLzQGzl9hGAs+/+rIAlGUW9W8vB1NCGL3k15mE+7F12aPzn0jLqqnUrxpLGsfC5CbLHXZ1xAp8nqYH7iK0fiqKau/R+MX3hSGjmsWdKUy/DZfeFsbCLiKOBvjg1Ru3cXE2V1F/GSx6wHVPEGK7hhxmlylRth4RkfxnBC9OerzAhyA2b4QmRlTseRL6AcgR/06qmO8BHyObHlizaBybU3Io+fxNq04bIjHQhhGlN+l9zX00y7Ww+/T+AquNn+aZPG5uUQdaHLzwnH5hPjjrsgm4ZgS2DDH/1waRScq2rwJkV2JU=
  on:
    tags: true
    python: 3.6
jobs:
  include:
    - name: "ARM, Python: 3.7"
      arch: "arm64"
      python: "3.7"
      before_install:
        - python -m pip install virtualenv
        - python -m virtualenv venv
        - source venv/bin/activate
        - python -m pip install twine==2.0.0
# Travis' OS X nodes are not yet stable enough to run this consistently
#    - name: "OS X, Python: 3.7"
#      os: "osx"
#      language: shell
#      osx_image: "xcode11.2"
#      before_install:
#        - python3 -m pip install virtualenv
#        - python3 -m virtualenv .ven
    - name: "Windows, Python: 3.7"
      os: "windows"
      language: shell
      before_install:
        - git clone https://github.com/pyenv-win/pyenv-win.git $HOME/.pyenv
        - export PATH="$HOME/.pyenv/pyenv-win/bin:$HOME/.pyenv/pyenv-win/shims:$PATH"
        - pyenv install -q 3.7.2
        - pyenv global 3.7.2
        - pyenv rehash
        - pyenv local 3.7.2
        - python --version
        - export PATH="$HOME/.pyenv/pyenv-win/versions/3.7.2/Scripts:$PATH"
      install:
        - pip install -r requirements.txt -r requirements-dev.txt
      script:
        - nosetests -s